- hosts: localhost
  gather_facts: true
  roles:
    - role: ansible-role-openvpn
      openvpn_port: 4300
      openvpn_sync_certs: true
      openvpn_local: ovpno.duckdns.org
      openvpn_server_hostname: ovpno.duckdns.org
      clients:
        - Vienna
        - Gais
